### ISSUE TITLE
Waiting for a branch to finish all checks before running

### ISSUE THREAD

**Issue by te-online** [jitterbit/await-check-suites#1]
Thanks a lot for publishing this action!

Can this action be used to wait for actions on one branch, so they're only ever run sequentially? I tried this config, but it doesn't seem to find other running checks (maybe because they're from another commit?).

``` YAML
- uses: jitterbit/await-check-suites@v1
  with:
    # The commit's ref (can be a SHA, branch name, or a tag name).
    # Default: ${{ github.sha }}
    ref: 'dev'

    # Wait for a check suite to be created if none exist.
    # This is important to protect against race conditions
    # if you know a check suite should exist on the `ref`'s commit.
    # Default: true
    waitForACheckSuite: false

    # Number of seconds to wait before timing out.
    timeoutSeconds: 3600

    # Fail step if any of the check suites complete with a conclusion other than 'success'.
    # Default: true
    failStepIfUnsuccessful: false
```

I pushed to `dev` in short sequence and two checks were running. Result:

```
Run jitterbit/await-check-suites@v1
No check suites (excluding this one) exist for this commit.
Conclusion: success
```

**Comment by sean-krail** [comment]
Hey @te-online, thanks for using the action! Sorry for the late reply. Not sure why I didn't get a notification...

That's exactly the problem this action is meant to solve. In fact there's an automated test that checks for this exact use case (https://github.com/jitterbit/await-check-suites/blob/master/.github/workflows/test.yml#L78-L118).

Not sure why it isn't working for you. Some questions I have for you that may seem obvious:
1. Is the `dev` branch on the same repo that is running the action?
2. Can you verify that there are status checks on this branch at the time it is run? You may want to try setting `waitForACheckSuite` to `true`. There's a slight delay in time between when the commit gets pushed and when the status checks are created.

**Comment by te-online** [comment]
Thanks for getting back to me. Didn't have time to look at your answer thoroughly. 

Re. 1. Yes, it's on the same repo. 

I have this in the yaml-file
```
on:
  push:
    branches:
      - dev
```

But the problem might just be that I don't fully understand Github Actions, yet.

Re. 2. I'll check that out, thanks!

**Comment by te-online** [comment]
I was able to make it work more reliably 😊 
Using this workflow file:

```YAML
on:
  push:
    branches:
      - dev
name: Deploy dev branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: jitterbit/await-check-suites@v1
        with:
          # The commit's ref (can be a SHA, branch name, or a tag name).
          # Default: ${{ github.sha }}
          ref: 'dev'

          # Wait for a check suite to be created if none exist.
          # This is important to protect against race conditions
          # if you know a check suite should exist on the `ref`'s commit.
          # Default: true
          # waitForACheckSuite: true

          # Number of seconds to wait before timing out.
          timeoutSeconds: 15

          # Fail step if any of the check suites complete with a conclusion other than 'success'.
          # Default: true
          failStepIfUnsuccessful: false
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
...
```

I lowered the timeout to 15 seconds, because I realized that it's the timeout to wait for a “green light“ (in lack of a better term). If within this timeout there's still another check suite running, it's just going to fail the later test suite, which is what I expected.

However, I was still able to reproduce the race-condition (even though `waitForCheckSuite` is no longer set to `false`) that when two checks of type `Run jitterbit/await-check-suites@v1` for some reason run at the very same time in two check suites triggered by `dev`, at first they seem to block each other from doing anything and then they both proceeded at some point. I guess this happens because none of the check-suites knows if it has priority over the other, right? But shouldn't that fail both of them? Maybe I'm missing something here 🤔
